### PR TITLE
[ubuntu-dev] upgrade to node 10.0.0

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by jankeromnes** [comment]
Oops, Theia purposefully rejects Node 10:

```
Step 48/53 : RUN cd /home/user/.theia/  && yarn  && yarn theia build
 ---> Running in 40ce592f0c30
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning @theia/core > @types/perfect-scrollbar@1.3.0: This is a stub types definition for perfect-scrollbar (https://github.com/noraesae/perfect-scrollbar). perfect-scrollbar provides its own type definitions, so you don't need @types/perfect-scrollbar installed!
warning @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
warning @theia/extension-manager > @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning @theia/extension-manager > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning @theia/extension-manager > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/extension-manager > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/go > @theia/core > @types/perfect-scrollbar@1.3.0: This is a stub types definition for perfect-scrollbar (https://github.com/noraesae/perfect-scrollbar). perfect-scrollbar provides its own type definitions, so you don't need @types/perfect-scrollbar installed!
warning @theia/go > go-language-server > json-rpc2 > es5class@2.3.1: this package isn't maintained anymore because ES6+
[2/4] Fetching packages...
warning vscode-base-languageclient@0.0.1-alpha.5: The engine "vscode" appears to be invalid.
error upath@1.0.4: The engine "node" is incompatible with this module. Expected version ">=4 <=9".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd /home/user/.theia/  && yarn  && yarn theia build' returned a non-zero code: 1
Exited with code 1
```

**Comment by jankeromnes** [comment]
Well, its dependency `upath@1.0.4` does.

**Comment by jankeromnes** [comment]
Fixed in https://github.com/anodynos/upath/pull/15 and awaiting merge (this currently prevents all projects using `webpack` from using Node 10!)

**Comment by anodynos** [comment]
Hello everyone - I fixed [upath](https://github.com/anodynos/upath/pull/15) & published it  - thanks & sorry for the delay! You can close the issue, once you check its working.

**Comment by jankeromnes** [comment]
Now waiting for every package in the dependency chain between `upath` and Theia to upgrade.

**Comment by ishitatsuyuki** [comment]
Theia's dependency, `nsfw` is currently broken with Node 10.

**Comment by jankeromnes** [comment]
Seems to be fixed, and we're now using `node 10.13.0 LTS`! :tada:

**Pull request closed without merging**
