### PR TITLE
[firefox-hg] clone mozilla-unified instead of mozilla-central

### PR DESCRIPTION
**Pull request by jankeromnes**

### CODE REVIEW

**Comment by nt1m** [comment]
I don't find mozilla-unified more convenient to use than mozilla-central IMO.

**Comment by nt1m** [comment]
As mozilla-unified uses a more modern Mercurial workflow (that some MDN pages are not up to date with) and has all mozilla repos in one. It's surely less confusing to use mozilla-unified for new contributors.

**Comment by jankeromnes** [comment]
It allows to do stuff like `hg rebase -b <commit> -d inbound`.

Here is a related IRC discussion (in French):

> 11:02:18 <&janx> padenot: j'avais fait `hg import patch.diff` pour importer un commit git, puis je voulais le rebase, donc j'ai fait `hg pull -u`, mais je vois plus mon commit, il est où ? :) comment je le remet tout en haut pour l'envoyer en review ?
> 11:02:31 <&bbouvier> janx, hg heads
> 11:02:55 <&padenot> janx, il fallait pas faire pull -u
> 11:02:59 <&bbouvier> janx, hg rebase -b [hash ou identifiant de ton commit] -d inbound
> 11:03:00 <&padenot> janx, pull -u, c'est pull + update
> 11:04:01 <&janx> bbouvier: ah cool, y a rebase ! mais "abort: unknown revision 'inbound'!"
> 11:04:11 <&padenot> janx, quel type de tree tu as cloné ?
> 11:04:23 <&padenot> apparement pas mozilla-unified
> 11:04:50 <&janx> padenot: mozilla-central https://github.com/JanitorTechnology/dockerfiles/blob/e07de2e18b0bce19/firefox/firefox-hg.dockerfile#L13
> 11:05:01 <&padenot> oui donc tu n'as pas toute les branches bien taggées
> 11:05:02 <&janx> mozilla-unified c'est mieux ?
> 11:05:07 <&padenot> beaucoup mieux
> 11:05:35 <&janx> ok je vais changer le dockerfile de janitor alors

The conclusions I draw from this: `hg pull -u` in our `janitor-hg.json` is not ideal and should be replaced, and cloning `mozilla-unified` would be better than `mozilla-central` because it has properly tagged branches.

**Comment by jankeromnes** [comment]
@nt1m Thanks a lot for your input on this change! If it doesn't break your workflow, could you please approve it? Thanks 😄

**Pull request merged**
