### PR TITLE
Removed not supported Heredoc

### PR DESCRIPTION
**Pull request by beaufortfrancois**
FIX https://github.com/JanitorTechnology/dockerfiles/issues/143

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Here's the preview: https://github.com/JanitorTechnology/dockerfiles/compare/HEAD%5E1...beaufortfrancois:be02320ca024e6ef93a47a40874a06a4ddb5a7f7

**Comment by jankeromnes** [comment]
Thanks a lot! I'll have a look now.

**Comment by jankeromnes** [comment]
> Here's the preview: HEAD^1...beaufortfrancois:7fd66ec

Ha, this was much easier to review. Which I'd started there. 😛

**Comment by jankeromnes** [comment]
@beaufortfrancois Hmm, it failed again, but the problem doesn't look related to your changes:

```
Step 9/17 : RUN fetch --nohooks chromium
 ---> Running in 8039642c7037
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/chromium/src.git",
    "managed": False,
    "name": "src",
    "deps_file": ".DEPS.git",
    "custom_deps": {},
  },
]
Traceback (most recent call last):
  File "/home/user/depot_tools/gclient.py", line 2917, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/home/user/depot_tools/gclient.py", line 2903, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/home/user/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/home/user/depot_tools/gclient.py", line 2488, in CMDconfig
    client.SaveConfig()
  File "/home/user/depot_tools/gclient.py", line 1507, in SaveConfig
    self.config_content)
  File "/home/user/depot_tools/gclient_utils.py", line 150, in FileWrite
    with codecs.open(filename, mode=mode, encoding='utf-8') as f:
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 13] Permission denied: './.gclient'
Traceback (most recent call last):
  File "/home/user/depot_tools/fetch.py", line 306, in <module>
    sys.exit(main())
  File "/home/user/depot_tools/fetch.py", line 301, in main
    return run(options, spec, root)
  File "/home/user/depot_tools/fetch.py", line 295, in run
    return checkout.init()
  File "/home/user/depot_tools/fetch.py", line 129, in init
    self.run_gclient('config', '--spec', self._format_spec())
  File "/home/user/depot_tools/fetch.py", line 82, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/home/user/depot_tools/fetch.py", line 71, in run
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('gclient', 'config', '--spec', u'solutions = [\n  {\n    "url": "https://chromium.googlesource.com/chromium/src.git",\n    "managed": False,\n    "name": "src",\n    "deps_file": ".DEPS.git",\n    "custom_deps": {},\n  },\n]\n')' returned non-zero exit status 1
'
The command '/bin/sh -c fetch --nohooks chromium' returned a non-zero code: 1
Exited with code 1
```

**Comment by beaufortfrancois** [comment]
It is sadly. I'll submit a PR shortly.

**Comment by beaufortfrancois** [comment]
See https://github.com/JanitorTechnology/dockerfiles/pull/145

**Comment by jankeromnes** [comment]
Indeed, and thanks! Merged. :)

**Pull request merged**
