### PR TITLE
[ubuntu-dev] install the latest gcc-6 for all images

### LINKED ISSUE #180: [fennec] upgrade to GCC 6.1 or newer
The Fennec build is currently broken on Circle CI:

```
 0:02.06 checking the target C compiler version... 6.0.0
 0:02.24 checking the target C compiler works... yes
 0:02.24 checking for the target C++ compiler... /usr/bin/clang++-6.0
 0:02.32 checking whether the target C++ compiler can be used... yes
 0:02.32 checking the target C++ compiler version... 6.0.0
 0:02.39 checking the target C++ compiler works... yes
 0:02.39 checking for the host C compiler... /usr/bin/gcc
 0:02.42 checking whether the host C compiler can be used... no
 0:02.43 ERROR: Only GCC 6.1 or newer is supported (found version 5.4.0).
 0:02.45 *** Fix above errors and then restart with\
 0:02.45                "/usr/bin/make -f client.mk build"
 0:02.45 client.mk:145: recipe for target 'configure' failed
 0:02.45 make: *** [configure] Error 1
The command '/bin/sh -c ./mach build  && ./mach package' returned a non-zero code: 2
Exited with code 2
```

### PR DESCRIPTION
**Pull request by jankeromnes**
Should fix #180.

### CODE REVIEW

**Comment by jankeromnes** [comment]
Ok, `ubuntu-dev` builds and successfully installs `gcc-6` and `g++-6`, but Fennec still uses `gcc` which links to `gcc-5`.

We should make `gcc` point to `gcc-6` in the Fennec image. (Or maybe in all images?)

**Comment by jankeromnes** [comment]
`gcc-5` comes from `build-essential`. @ishitatsuyuki what are your thoughts on:

1. Replacing `build-essential` with `gcc-6, g++-6, libc6-dev, dpkg-dev, make` in order to no longer install `gcc-5`; versus
2. Just updating Fennec's alternatives to prefer `gcc-6` over `gcc-5`?

**Comment by ishitatsuyuki** [comment]
Can I suggest wait until 26th and use Ubuntu 18.04? :P

**Comment by jankeromnes** [comment]
Why specifically the 26th? Also, maybe let's still fix Fennec build now (it's a really quick change), because maybe migrating to Ubuntu 18.04 will give us a few challenges on some projects.

**Comment by ishitatsuyuki** [comment]
We have three options:

- Wait for Ubuntu 18.04 release (Chromium's script only support Ubuntu LTS and current)
- Use Ubuntu 17.10
- Install a backported compiler

In the case of backported compiler, may I suggest to install it only in fennec?

**Comment by jankeromnes** [comment]
New approach: Only install `g++-6` and `gcc-6` for the Fennec image.

**Comment by jankeromnes** [comment]
Actually, maybe we don't even need GCC 6: it seems we could just define `HOST_CC=clang-6.0` and `HOST_CXX=clang++-6.0`, as suggested in [this bugzilla comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1451312#c7).

@ishitatsuyuki any thoughts on defining these in `ubuntu-dev`? 😄

**Comment by ishitatsuyuki** [comment]
That's sounds like a good solution.

**Comment by jankeromnes** [comment]
Fixes Fennec build, and KDE / Rust failures seem unrelated. Merging. 🚀

**Pull request merged**
