### PR TITLE
Add kde to circle ci jobs; update kde submodule

### PR DESCRIPTION
**Pull request by rcatolino**

### CODE REVIEW

**Comment by jankeromnes** [comment]
Woohoo! Thanks for this pull request. Hopefully it will allow us to automate KDE's very long-to-build image.

The CI shows that the `ubuntu-dev` build failed, but it doesn't seem related to your change:

```
Step 44/50 : RUN cd /home/user/.theia/  && yarn  && yarn theia build
 ---> Running in 8b4f78e046be
yarn install v1.5.1
info No lockfile found.
[1/4] Resolving packages...
warning @theia/typescript > @theia/core > @types/perfect-scrollbar@1.3.0: This is a stub types definition for perfect-scrollbar (https://github.com/noraesae/perfect-scrollbar). perfect-scrollbar provides its own type definitions, so you don't need @types/perfect-scrollbar installed!
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0: 
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@theia/file-search/-/file-search-0.4.0-next.bace685a.tgz: Request failed \"503 Service Unavailable\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/user/.theia/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c cd /home/user/.theia/  && yarn  && yarn theia build' returned a non-zero code: 1
Exited with code 1
```

I'll re-trigger in case this was temporary.

**Comment by jankeromnes** [comment]
I've rebased your commit on top of d620d685315e066658740fde2ae4acd454576bd8, which should fix the CircleCI pull request build, which should tell us if the KDE image is able to build. 😄

**Comment by jankeromnes** [comment]
Oops, KDE image build failed with:

```
#!/bin/sh -eo pipefail
docker load -i ubuntu-dev.tar
git submodule update --rebase --remote kde
./.circleci/build_image.sh kde/dockerfile janitortechnology/kde

Loaded image: janitortechnology/ubuntu-dev:latest
/bin/sh: git: not found
Exited with code 127
```

Maybe we should add an extra step like `apt-get -qq update && apt-get -qy install git`?

**Comment by jankeromnes** [comment]
Thanks a lot for fixing these small issues! Here are a few more issues from our CI build:

```
#!/bin/sh -eo pipefail
docker load -i ubuntu-dev.tar
git submodule update --rebase --remote kde
./.circleci/build_image.sh kde/dockerfile janitortechnology/kde

Loaded image: janitortechnology/ubuntu-dev:latest
Submodule path 'kde' not initialized
Maybe you want to use 'update --init'?
+ [[ 2 -ne 2 ]]
+ dirname kde/dockerfile
+ DIR=kde
+ DOCKERFILE=kde/dockerfile
+ IMAGE_NAME=janitortechnology/kde
+ docker build -t janitortechnology/kde -f kde/dockerfile kde
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/project/kde/dockerfile: no such file or directory
Exited with code 1
```

**Comment by jankeromnes** [comment]
Nice, KDE image built successfully! :+1: :tada:

(In under 25min if you believe it. Did you build fewer things for testing?)

**Comment by rcatolino** [comment]
Yes, this is with the changes from @adriaandegroot , the sources are pulled but not built.

**Comment by jankeromnes** [comment]
> Yes, this is with the changes from @adriaandegroot , the sources are pulled but not built.

Won't KDE developers usually need to build the sources? (I'd like our project images to include as much pre-work as possible; If there is any task that a developer will typically need to run, and we can do it form them beforehand (even partially, by pre-warming `ccache` or something), I think we should do it in the Dockerfile.)

On the other hand, if building KDE sources takes too long for CircleCI, we can also skip the build in the main Dockerfile, but update & build the sources on our own servers with an "update" Dockerfile (just like we do for Chromium, see its [main dockerfile](https://github.com/JanitorTechnology/dockerfiles/blob/159f86f686a841c6eceebec0ce7a3b5992c9c743/chromium/chromium.dockerfile#L43) without ninja build, and its [update dockerfile](https://github.com/JanitorTechnology/dockerfiles/blob/159f86f686a841c6eceebec0ce7a3b5992c9c743/chromium/chromium-update.dockerfile#L16) with ninja build).

**Comment by adriaandegroot** [comment]
Well, the thing is that (a) KDE is huge (b) KDE is a bit of a misnomer, since "KDE" is the community, which produces a whole bunch of different bits of software; there's about 80 KDE Frameworks, which are underlying libraries and which build in .. possibly reasonable time; there's KDE Plasma Desktop, which builds on the frameworks; there's the KDE applications, another 140 of them or so. It is not one monolithic thing like, say, the Thunderbird container. Sure, you could build everything in advance, but that's 2G or more of source to grind through.

**Comment by jankeromnes** [comment]
Thank you for these insights!

I understand that there are many different KDE frameworks, and that it might make more sense to produce different images for different needs (e.g. for different KDE sub-communities). I'd love to find out where the sweet spot is between a gigantic behemoth image and a swarm of tightly-scoped images. (Or maybe the swarm is the sweet spot?)

That being said, the size of the image should really not be a factor here, because our servers can definitely handle them, and it's ok if building and/or transferring them is slow, because that happens in the background where nobody watches (as long as developers can create new containers in < 2 seconds, with everything that they'd need already pre-compiled, and the availabe project images remain relatively fresh, I think we win).

I think that this pull request is about ready to be merged, and I'll try to give it a final pass tomorrow and deploy a new KDE image so that you and others can test it and get a better feeling for what it can do.

Thanks again for everyone that's helped so far! This is really exciting. :smile:

**Pull request merged**
